Repository cmu-sei/Gameboard, pull requests merged in 2023-03, with the labels that each got.

#128 Add Swagger PKCE support
  src/Gameboard.Api/Extensions/SwaggerStartupExtensions.cs
Labels: chores

#144 Disable anonymous access to version endpoint
  src/Gameboard.Api/Features/Version/VersionController.cs
Labels: enhancement

#143 Improvements to Admin/Challenges
  .vscode/tasks.json
  Gameboard.sln
  src/Gameboard.Api.Tests.Shared/Fixtures/GameboardCustomization.cs
  src/Gameboard.Api.Tests.Shared/Gameboard.Api.Tests.Shared.csproj
  src/Gameboard.Api/Data/Entities/Challenge.cs
  src/Gameboard.Api/Data/Entities/ChallengeSpec.cs
  src/Gameboard.Api/Data/Migrations/PostgreSQL/GameboardDb/GameboardDbContextPostgreSQLModelSnapshot.cs
  src/Gameboard.Api/Extensions/SwaggerStartupExtensions.cs
  src/Gameboard.Api/Features/Challenge/Challenge.cs
  src/Gameboard.Api/Features/Challenge/ChallengeMapper.cs
  src/Gameboard.Api/Features/Challenge/ChallengeService.cs
  src/Gameboard.Api/Program.cs
  src/Gameboard.Tests.Unit/Fixtures/GameboardAutoDataAttribute.cs
  src/Gameboard.Tests.Unit/Gameboard.Tests.Unit.csproj
  src/Gameboard.Tests.Unit/Tests/Features/Challenges/ChallengeMapperTests.cs
  src/Gameboard.Tests.Unit/Tests/Features/GameEngine/GameEngineMapsTests.cs
  src/Gameboard.Tests.Unit/Tests/Features/User/UserServiceTests.cs
Labels: bug, enhancement
